# Generated by Django 3.2.5 on 2022-07-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesByCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.IntegerField()),
                ('card_type', models.CharField(max_length=50)),
                ('total_sales', models.FloatField()),
            ],
        ),
    ]
